Add missing inactiveSeedingTimeLimit parameter to section setShareLimits in WebUI API wiki
qbittorrent/wiki pull request #4
Opened 2024-05-12 11:25 UTC by antonkvm

Updates the ['Set share limit'](https://github.com/qbittorrent/qBittorrent/wiki/WebUI-API-(qBittorrent-4.1)#set-torrent-share-limit) section in the WebUI API wiki:

Changes:
- Adds the `inactiveSeedingTimeLimit` parameter to the WebUI API wiki page, which was missing before
- organizes the parameters in a table for better readability
- revises parameter descriptions slightly to be more concise
- mentions missing parameter scenario for response error code 400 Bad Request

The `inactiveSeedingTimeLimit` parameter was added in v4.6.0, but not added to the wiki, which meant that previously functional requests would now return error code 400 because of the missing parameter.

Addresses issues [#20787](https://github.com/qbittorrent/qBittorrent/issues/20787) and  [#20110](https://github.com/qbittorrent/qBittorrent/issues/20110) in the [main qBittorent repo](https://github.com/qbittorrent/qBittorrent).

2024-05-12 11:56 UTC, xavier2k6 requested changes

2024-05-12 11:56 UTC, xavier2k6 commented on WebUI-API-(qBittorrent-4.1).md
> +`hashes`                      | integer | The hashes of the torrents for which you want to set the share limits. Multiple hashes need to be seperated by `\|` or set to `all`.
typo: `seperated` -> `separated`

2024-05-13 00:34 UTC, antonkvm commented on WebUI-API-(qBittorrent-4.1).md
> +`hashes`                      | integer | The hashes of the torrents for which you want to set the share limits. Multiple hashes need to be seperated by `\|` or set to `all`.
Fixed typo in new commit

2024-05-13 13:06 UTC, merged

2024-05-13 13:07 UTC, xavier2k6 commented
@antonkvm Thank you!